### ISSUE TITLE
object-size library is giving error

### ISSUE THREAD

**Issue by JijiyaT** [angular-architects/module-federation-plugin#822]
### With what library do you have an issue?

native-federation

### Reproduction of the bug/regression with instructions

After upgrading from NF and Angular from 17 to version 19.0.16 ,we are facing issues with buffer,lodash,json-rules-engine and object-sizeof libraries.

Out of them we could not able to identify how to resolve below error with object-sizeof.

main.ts:6 Error: Dynamic require of "buffer/" is not supported
    at object_sizeof.zvnha0tKV9-dev.js:6:9
    at node_modules/object-sizeof/indexv2.js (object_sizeof.zvnha0tKV9-dev.js:39:51)
    at __require2 (object_sizeof.zvnha0tKV9-dev.js:9:50)
    at object_sizeof.zvnha0tKV9-dev.js:136:16

### Expected behavior

It should work normally even after migration

### Versions of Native/Module Federation, Angular, Node, Browser, and operating system

Native: 19.0.16
Angular: 19 - Not working even tried with 19.1 and 19.2 as well
Node: 22.14
OS: Brave

### I would be willing to submit a PR to fix this issue

- [ ] Yes
- [ ] No

**Comment by JijiyaT** [comment]
@manfredsteyer  Please look into this and provide us some solution.

**Comment by manfredsteyer** [comment]
Can you please try to import via the default import:

Instead:
import {x} from 'my-lib'

Please try this:
import myLib from 'my-lib';
const x = myLib.x;

If this helps, it's due to the fact that these libs are still commonjs.

**Comment by JijiyaT** [comment]
Hi @manfredsteyer 

The libraries(mqtt, object-sizeof) can be converted to ESM but the dependent libraries are not able to convert into ESM as they are using old require syntax for buffer.

As already mentioned onject-sizeof using old require syntax in its code to import buffer

 var Buffer2 = typeof window !== "undefined" ? __require("buffer/").Buffer : global.Buffer;

Is there any other way we can use them in our code.We dont want to skip them.

And one more question,From which exact version NF started excluding node.js libraries.

**Comment by manfredsteyer** [comment]
I see. I need to look at an example. Can you please provide a minimal reproduction via github?

Does excluding Node.js libs lead to an issue for you?

**Comment by JijiyaT** [comment]
@manfredsteyer 

You just need to import object-sizeof and use it in the code.
Below github code shows

 https://github.com/JijiyaT/Angular-NativeFederation19/commit/f8c35f28dcad4a4d51c14644409c22b39ef76021

our project working fine in 17.Just wondering on the changes that's causing the issue with these libraries.

**Comment by manfredsteyer** [comment]
Hi,

Thanks for the reproduction.

It seems like, it works with the newest Native Federation version, if you point it to the ESM version of mqtt:

```js
  shared: {
    ...shareAll({ singleton: true, strictVersion: true, requiredVersion: 'auto' }),
    'mqtt': {
      packageInfo: {
        entryPoint: 'mqtt/dist/mqtt.esm',   // no .js here at the end!!
        version: '5.10.4',
        esm: true,
      },
    },
  },
```

Also, in your app.component.ts, please switch out MqttClient for Client:

```ts
  static client: mqtt.Client | null = null; 
    // Client i/o MqttClient !!
```

**Comment by manfredsteyer** [comment]
Btw: `object-size` needs some work, however. I have analyzed it and I think we can have a solution very soon.

**Comment by JijiyaT** [comment]
@manfredsteyer 

Thank you for the update.

**Comment by JijiyaT** [comment]
@manfredsteyer  Is there any update on this issue with new released version.

**Comment by manfredsteyer** [comment]
Can you please retry with the newest NF version?
Please also nuke node_modules/.cache before.
