### ISSUE TITLE
@angular-architects/module-federation-tools@~14.3.10 version not working with @angular/core@~13.3.11 -- It was working till after noon 17Oct-2022

### ISSUE THREAD

**Issue by pvasantha** [angular-architects/module-federation-plugin#246]
./node_modules/@angular-architects/module-federation-tools/fesm2015/angular-architects-module-federation-tools.mjs - Error: Module build failed (from ./node_modules/@angular-devkit/build-angular/src/babel/webpack-loader.js):
TypeError: Cannot create property 'message' on string test-ui/node_modules/@angular-architects/module-federation-tools/fesm2015/angular-architects-module-federation-tools.mjs: This application depends upon a library published using Angular version 14.1.1, which requires Angular version 14.0.0 or newer to work correctly.
Consider upgrading your application to use a more recent version of Angular

Error: node_modules/@angular-architects/module-federation-tools/lib/web-components/web-component-wrapper.d.ts:25:18 - error TS2314: Generic type 'ɵɵComponentDeclaration' requires 7 type argument(s).

25     static ɵcmp: i0.ɵɵComponentDeclaration<WebComponentWrapper, "mft-wc-wrapper", never, { "options": "options"; "props": "props"; "events": "events"; }, {}, never, never, false>;

**Comment by r1m** [comment]
Use ` "@angular-architects/module-federation": "~14.2.3",` with angular 13.
Version 14.3 is for angular 14
